baseurl = "/" # https://openscapes.org
title = "Openscapes"
theme = "hugo-universal-theme"
publishDir = "public"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Champions Program"
    identifier = "champions"
    url  = "/champions/"
    weight = 1    

[[menu.main]]
    name = "Resources"
    identifier = "resources"
    url  = "/resources/"
    weight = 2  

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 4

[[menu.main]]
    name = "Get Involved"
    url  = "/contact/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/openscapes"
    pre = "<i class='fa fa-2x fa-github'></i>"

#[[menu.topbar]]
#    weight = 2
#    name = "Facebook"
#    url = "http://facebook.com"
#    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com/openscapes"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:openscapes@nceas.ucsb.edu"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Openscapes"
    defaultKeywords = ["openscapes", "mozilla", "nceas"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    #Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    # email = "your@email.com"

    about_us = "<p>Our vision is a scientific culture that is more efficient and collaborative, and can uncover environmental solutions faster. Openscapes is operated by the National Center for Ecological Analysis & Synthesis (NCEAS) and is being incubated by a Mozilla Fellowship awarded to Julia Lowndes.</p>"
    copyright = "Copyright (c) 2018, Openscapes; all rights reserved." 

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p><strong>Openscapes</strong>
        <br>National Center for Ecological
        <br>Analysis & Synthesis (NCEAS)
        <br>University of California
        <br>Santa Barbara, California, USA
        <br>----
        <br>openscapes @ nceas.ucsb.edu
        <br>Twitter & GitHub: @openscapes
      </p>
      """ 
    latitude = ""
    longitude = ""
 
[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.
    title = "What we do"
    subtitle = "**At Openscapes, we champion open practices in environmental science to uncover data-driven solutions faster**. No matter the research question, environmental scientists are united by the need to analyze data — and do so in a way that is efficient, reproducible, and easily communicated. With open tools and practices specifically created to meet modern demands for collaborative data science, we enable better science in less time. Here's how:"

[params.testimonials] 
    enable = false  
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Champions Program"
    subtitle = "."

 [params.testimonials2]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README. 
    title = "Champions Program" 
    subtitle = "Openscapes Champions is a mentorship program that empowers environmental scientists with open data science tools and grows the community of practice in their labs and departments."

 [params.workshops]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README. 
    title = "Workshops" 
    subtitle = "We plan to also teach the Champions lessons series as short-form workshops. If you are interested, please contact us."


[params.testimonials3]  
    enable = true 
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README. 
    title = "Vision & Ethos"
    subtitle = "**Our vision is a scientific culture that is more efficient and collaborative, and can uncover environmental solutions faster.** Openscapes opens the landscapes of science through community, data, and code. This means promoting open science: open data, open knowledge, and using the internet for good. It also means open culture: collaboration, empathy, and kindness. We aim to create a positive open culture in science, so we can do better science in less time." 
    # title = "Trainings and Workshops"
    # subtitle = "We will also do Trainings and Workshops..."


[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Openscapes is operated by NCEAS and incubated by Mozilla"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "These are blog posts and advice snippets for the Openscapes community. Some are cross-posted on [Medium.com](https://medium.com/@openscapes)."
